apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-all
spec:
  params:
    - description: password of the target image repository
      name: repository-password
      type: string
    - description: source branch/tag to use to compile the stuff
      name: git-revision
      type: string
      default: main
    - name: config-git-revision
      type: string
      description: The revision of the config repo to use
      default: main
  tasks:
    - name: start-server-build
      params:
        - name: ARGS
          value:
            - build-server
            - '-s pipeline-bot'
            - '-p repo-password=$(params.repository-password)'
            - '-p git-revision=$(params.git-revision)'
            - '-p config-git-revision=$(params.config-git-revision)'
            - '-w name=source,claimName=builder-pvc'
            - '-w name=maven-settings,config=maven-settings'
            - '--use-param-defaults'
      taskRef:
        kind: Task
        name: start-pipeline

      
    - name: start-client-build
      params:
        - name: ARGS
          value:
            - build-client
            - '-s pipeline-bot'
            - '-p repo-password=$(params.repository-password)'
            - '-p git-revision=$(params.git-revision)'
            - '-p config-git-revision=$(params.config-git-revision)'
            - '-w name=source,claimName=client-builder-pvc'
            - '-w name=maven-settings,config=maven-settings'
            - '--use-param-defaults'
      taskRef:
        kind: Task
        name: start-pipeline

    - name: wait-for-client
      runAfter:
        - start-client-build
      taskRef:
        kind: Task
        name: kubernetes-actions
      params:
        - name: script
          value: kubectl $@
        - name: args
          value:
            - wait
            - '--for=condition=Succeeded'
            - '--timeout=400s'
            - 'PipelineRun/$(tasks.start-client-build.results.PIPELINE_RUN_ID)'

    - name: wait-for-server
      runAfter:
        - start-server-build
      taskRef:
        kind: Task
        name: kubernetes-actions
      params:
        - name: script
          value: kubectl $@
        - name: args
          value:
            - wait
            - '--for=condition=Succeeded'
            - '--timeout=400s'
            - 'PipelineRun/$(tasks.start-server-build.results.PIPELINE_RUN_ID)'

    - name: start-argocd-sync
      params:
        - name: application-name
          value: cat-dev
        - name: revision
          value: "$(params.config-git-revision)"
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v2.2.2
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
      runAfter:
        - wait-for-client
        - wait-for-server


