apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  name: git-update-deployment
  labels:
    app.kubernetes.io/version: '0.3'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image digest in a Git repo using kustomize. It requires a secret with credentials for accessing the git repo.
  params:
    - name: CURRENT_IMAGE
      type: string
    - name: NEW_IMAGE
      type: string
    - name: NEW_DIGEST
      type: string
    - name: KUSTOMIZATION_PATH
      type: string
    - name: GIT_REVISION
      type: string
      default: main

  workspaces:
    - description: The workspace consisting of maven project.
      name: workspace

  results:
    - name: commit
      description: The commit SHA

  steps:
    - name: git-pull
      image: docker.io/bitnami/git:2.45.0
      workingDir: $(workspaces.workspace.path)/the-config
      script: |
        echo "git revision: $(params.GIT_REVISION)"
        echo "config"
        git config --global --add safe.directory /workspace/workspace/the-config

        echo "status"
        git status

        echo "checkout"
        git checkout $(params.GIT_REVISION)

        echo "pull"
        git pull origin $(params.GIT_REVISION)

    - name: update-digest
      image: quay.io/wpernath/kustomize-ubi:latest
      workingDir: $(workspaces.workspace.path)/the-config
      script: |
        cd $(params.KUSTOMIZATION_PATH)
        kustomize edit set image $(params.CURRENT_IMAGE)=$(params.NEW_IMAGE)@$(params.NEW_DIGEST)

    - name: git-commit
      image: docker.io/bitnami/git:2.45.0
      workingDir: $(workspaces.workspace.path)/the-config
      script: |
        git config --global --add safe.directory /workspace/workspace/the-config
        git config user.email "wpernath@redhat.com"
        git config user.name "My Tekton Bot"

        git add $(params.KUSTOMIZATION_PATH)/kustomization.yaml
        git commit -am "[ci] Image digest updated"
        
        git push origin HEAD:$(params.GIT_REVISION)

        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
        EXIT_CODE="$?"
        if [ "$EXIT_CODE" != 0 ]
        then
          exit $EXIT_CODE
        fi
        # Make sure we don't add a trailing newline to the result!
        echo -n "$RESULT_SHA" > $(results.commit.path)
