apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-dev  
  namespace: cat-ci
spec:
  destination:
    namespace: cat-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/dev
    repoURL: https://github.com/wpernath/grumpycat-config.git
    targetRevision: aws-grumpycat
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-stage  
  namespace: cat-ci
spec:
  destination:
    namespace: cat-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/stage
    repoURL: https://github.com/wpernath/grumpycat-config.git
    targetRevision: aws-grumpycat
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-prod  
  namespace: cat-ci
spec:
  destination:
    namespace: cat-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/prod
    repoURL: https://github.com/wpernath/grumpycat-config.git
    targetRevision: aws-grumpycat
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - PruneLast=true
